### ISSUE TITLE
Self-unpinning tabs

### ISSUE THREAD

**Issue by DutchPete** [sethyuan/logseq-plugin-tabbed-sidebar#8]
I have 4 pinned tabs in the sidebar. When I open a page in the sidebar, the other 4 sometimes unpin.

Or, the other 4 stay pinned and the new page pins itself. I could not unpin it; had to “move up”, which undid the pinning so I could close it.

**Comment by sethyuan** [comment]
Strange, is this happening every time? Are you using the latest version of the plugin?

**Comment by DutchPete** [comment]
I am on version 0.10.4.

**Comment by sethyuan** [comment]
I don't know, do you see any error output in the console (ctrl+shift+i or cmd+shift+i) after the error happens?

Maybe try re-indexing?

**Comment by DutchPete** [comment]
I did not check the console for errors.
I have just ran a reindex, and this is what I got without adding a page to the sidebar:

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/10794265/adc89f98-85b1-42c9-89dd-70fe86b25fb3)

And this is what the Console shows:

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/10794265/857e6c0c-6564-4f8c-8182-a838b0ea0126)

**Comment by sethyuan** [comment]
Can you re-open Logseq, open the right sidebar and look at the console again?

**Comment by DutchPete** [comment]
Doing that only shows 1 odd tab:

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/10794265/8a2518db-e079-4d48-b3fd-3e1cafdb2a7c)

The Console shows mostly a long list of black text, which I assume means no problem. However, right at the bottom there is this:

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/10794265/437cc73c-1dab-4c18-8734-1a3f1d4c7a13)

**Comment by sethyuan** [comment]
These are fine, they not related to the plugin. What is that odd tab? What if you close it, will it appear again when you re-open the right sidebar?

**Comment by DutchPete** [comment]
Update: clicking on the `X` in that odd tab shows it is the contents tab. Clicking on it again closes the sidepanel, and when I reopen the sidepanel the odd tab is gone.

The amount of red text in the Console is a lot bigger again:

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/10794265/749de4e0-34be-46b3-98dc-81cee4d4e9ec)

**Comment by sethyuan** [comment]
It seems that there is error, I'll investigate. Can you click here?

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/3410293/2e0b3424-5aea-451c-a73a-8cd8a3b70789)

It'll help me debug.

**Comment by DutchPete** [comment]
Oof, that gives a very long list of js code.
[tab-sidebar.js.zip](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/files/12472747/tab-sidebar.js.zip)

**Comment by sethyuan** [comment]
Can you give me a screenshot of where the error points to?

**Comment by DutchPete** [comment]
I don't understand: which error do you mean?

**Comment by sethyuan** [comment]
When you click this here:

https://user-images.githubusercontent.com/3410293/264256984-2e0b3424-5aea-451c-a73a-8cd8a3b70789.png

It should take you to a specific line of code, I'd like to have a screenshot of that.

**Comment by DutchPete** [comment]
This?

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/10794265/c309a6e0-c885-48d8-acdc-1724ef8b4b7d)

**Comment by sethyuan** [comment]
Yes, exactly this. Give me some time, I'll come back with a fix.

**Comment by sethyuan** [comment]
@DutchPete , I published a new version, v0.10.6, hope it helps.

**Comment by DutchPete** [comment]
I updated the plug-in, relaunched Logseq, and re-indexed. I still get this:

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/10794265/b437c067-6f06-46ea-ad07-ae239d3993c0)

Note: the tab with the C is also the Contents tab.

I checked the Console: lots of black text, with at the bottom this:

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/10794265/5c579de6-87df-4275-82c9-6d57351c3221)

**Comment by sethyuan** [comment]
The errors are irrelevant, it seems OK.
You mean the pinned tabs are wrong? That these are not what you pinned? If so, you can go into the below folder, delete the json file corresponding to your graph:

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/3410293/5e63e2ab-29bd-4ca4-87b6-08c26cfc7165)

**Comment by DutchPete** [comment]
No, that is not what I mean. The pinned tabs are fine. It is just that the one on the right, Contents with a X, should not be there as the Contents is already shown in the "C" tab.

**Comment by sethyuan** [comment]
I see. The Contents page is a little special, I'll take a look.

**Comment by sethyuan** [comment]
@DutchPete , I published another fix, please update and close and reopen Logseq. This should fix the pinning of Contents page.

**Comment by DutchPete** [comment]
Unfortunately, it is still there after updating the plug-in, closing & restarting Logseq:

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/10794265/dd41e5ae-72b1-48d6-8ac6-d4f9731b6460)

When I subsequently opened a page in the sidepanel, I get this:

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/10794265/d744a535-c54d-4e38-980d-540a17473964)

The Console shows this:

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/10794265/d50c8759-65f1-437e-a992-28904e8c5570)

**Comment by sethyuan** [comment]
Be sure the plugin's version is 0.10.7. It could also be that the pinned one is not the correct "Contents" page, you can unpin it, close both "Contents" tabs, and open "Contents" again and pin it.

**Comment by DutchPete** [comment]
> It could also be that the pinned one is not the correct "Contents" page, you can unpin it, close both "Contents" tabs, and open "Contents" again and pin it.

I did that, and indeed it now seems to be behaving normally.

Could it be because I had added the letter C in the form of an emoji as an icon property to the Contents page? In any case, I have removed the icon, just to make sure.

Opening a new page in the sidepanel does not present a problem anymore.
Many thanks for your help and a useful plug-in.
